In [1]:
#!pip install pandas

# Gather all data

In [2]:
import csv
import json
import pandas as pd
from datetime import datetime
import numpy as np
from collections import Counter


import warnings
warnings.filterwarnings("ignore")


outputFolders = "../data_2019_processed/"

In [3]:
# Dataframe of all datasets
# initialize list of lists
datasets = [['0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs'],
            ['0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA'], 
            ['2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0'], 
            ['2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys'], 
            #['5FLZBTVAPwdq9QezHE2sVCJIs7p+r6mCemA2gp9jATk'], #does not have the file
            ['7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA'], 
            ['a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4'], 
            ['ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc'], 
            ['Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U'], 
            ['CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA'], 
            ['DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc'], 
            ['DHPqzSqSttiba1L3BD1cptNJPjSxZ8rXxF9mY3za6WA'], 
            ['dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY'], 
            ['HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo'], 
            ['jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw'], 
            ['JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I'], 
            ['K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8'], 
            ['oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q'], 
            ['pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM'], 
            ['PZCf1nfvhR+6fk+7+sPNMYOgb8BAMmtQtfoRS83Suc'], 
            ['QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ'], 
            ['rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw'], 
            ['RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI'], 
            ['SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4'], 
            ['VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is'], 
            ['Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw'], 
            ['XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA'], 
            ['YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw'], 
            ['ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM'], 
            ['ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY']]
  
# Create the pandas DataFrame
folders = pd.DataFrame(datasets, columns=['folder'])

#folders

In [4]:
test = pd.read_csv(outputFolders+"student_0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs.csv")

# Data pre-processing

In [5]:
allData = pd.DataFrame(columns=test.columns)
for indexFolder, folder in folders.iterrows():

    dataFLabel = pd.read_csv(outputFolders+"student_"+folder['folder']+".csv",
                   delimiter=',', encoding="utf8")
    
    print(Counter(dataFLabel['class']))
    # merge the data set if has both classes
    if('asleep' in Counter(dataFLabel['class'])):
        if(allData.empty):
            allData = dataFLabel
        else:
            #allData = allData.append(mergedDS, ignore_index=True)
            allData = pd.concat([allData, dataFLabel])
        
# print all
allData.to_csv(outputFolders+"allData_filtred.csv", sep=',', encoding='utf-8', index=False)
#allData.to_csv("dados2019/allData.csv", sep=',', encoding='utf-8', index=False)

Counter({'awake': 16236, 'asleep': 1757})
Counter({'awake': 8135, 'asleep': 3426})
Counter({'awake': 1918, 'asleep': 1465})
Counter({'awake': 11618, 'asleep': 7771})
Counter({'awake': 2426, 'asleep': 327})
Counter({'awake': 14719, 'asleep': 11848})
Counter({'awake': 21442, 'asleep': 3092})
Counter({'awake': 22887, 'asleep': 11016})
Counter({'awake': 18061, 'asleep': 8379})
Counter({'awake': 21111, 'asleep': 3373})
Counter({'awake': 1712})
Counter({'asleep': 14643, 'awake': 11377})
Counter({'awake': 18788, 'asleep': 7144})
Counter({'awake': 24257, 'asleep': 7616})
Counter({'awake': 19880, 'asleep': 3364})
Counter({'awake': 15902, 'asleep': 3693})
Counter({'asleep': 14527, 'awake': 7142})
Counter({'awake': 25922, 'asleep': 7422})
Counter({'asleep': 937, 'awake': 461})
Counter({'awake': 15715, 'asleep': 6344})
Counter({'awake': 17766, 'asleep': 5979})
Counter({'awake': 24330, 'asleep': 8588})
Counter({'awake': 11732, 'asleep': 977})
Counter({'asleep': 8833, 'awake': 6412})
Counter({'awake': 1871, 'asleep': 741})
Counter({'awake': 14161, 'asleep': 3265})
Counter({'awake': 13375, 'asleep': 5756})
Counter({'asleep': 36, 'awake': 23})
Counter({'awake': 17300, 'asleep': 6452})

In [6]:
allData

,activity,location,distanceHome,showActuation,timestamp,day_of_week,light,phone_lock,proximity,sound,time_to_next_alarm,class,timestamp2,minutes_day,sleep_time,wakeup_time,time_sleeping
0,Unknown,Other,0,False,2018-05-15 14:20:45,Tuesday,37,not locked,5,0,594000000.0,awake,1526390445,860,1020,660,64804
1,Unknown,Other,0,False,2018-05-15 14:20:45,Tuesday,37,not locked,5,0,594000000.0,awake,1526390445,860,1020,660,64804
2,Still,University,0,False,2018-05-15 14:21:15,Tuesday,35,not locked,5,5517,593940000.0,awake,1526390475,861,1020,660,64804
3,Still,University,0,False,2018-05-15 14:21:45,Tuesday,307,not locked,5,5517,593940000.0,awake,1526390505,861,1020,660,64804
4,Still,University,0,False,2018-05-15 14:22:15,Tuesday,42,not locked,5,5809,593880000.0,awake,1526390535,862,1020,660,64804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23747,Still,House,0,False,2018-06-13 12:14:37,Wednesday,8,locked,5,0,59999.0,awake,1528888477,734,0,0,0
23748,Still,House,0,False,2018-06-13 12:18:08,Wednesday,11,locked,5,0,420000.0,awake,1528888688,738,0,0,0
23749,Still,House,0,False,2018-06-13 12:19:08,Wednesday,11,locked,5,0,359999.0,awake,1528888748,739,0,0,0
23750,Still,House,0,False,2018-06-13 12:19:38,Wednesday,12,locked,5,0,359999.0,awake,1528888778,739,0,0,0
23751,Tilting,House,0,False,2018-06-13 12:20:08,Wednesday,0,locked,0,0,299998.0,awake,1528888808,740,0,0,0